-- MySQL Script generated by MySQL Workbench
-- Wed Feb 19 19:11:57 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema service_management
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema service_management
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `service_management` DEFAULT CHARACTER SET utf8 ;
USE `service_management` ;

-- -----------------------------------------------------
-- Table `service_management`.`CUSTOMERS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `service_management`.`CUSTOMERS` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `phone` VARCHAR(15) CHARACTER SET 'utf8' NOT NULL,
  `email` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `service_management`.`ADDRESSES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `service_management`.`ADDRESSES` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fk_customer_id` INT NOT NULL,
  `street` VARCHAR(100) NOT NULL,
  `city` VARCHAR(50) NOT NULL,
  `state` VARCHAR(50) NOT NULL,
  `postal_code` VARCHAR(20) NOT NULL,
  `country` VARCHAR(50) CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_customer_id_idx` (`fk_customer_id` ASC) VISIBLE,
  CONSTRAINT `fk_customer_id`
    FOREIGN KEY (`fk_customer_id`)
    REFERENCES `service_management`.`CUSTOMERS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `service_management`.`DEVICES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `service_management`.`DEVICES` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fk_customer_id` INT NOT NULL,
  `type` VARCHAR(50) CHARACTER SET 'utf8' NOT NULL,
  `brand` VARCHAR(50) COLLATE 'Default Collation' NOT NULL,
  `model` VARCHAR(50) NULL,
  `serial_number` VARCHAR(50) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_customer_id_idx` (`fk_customer_id` ASC) VISIBLE,
  CONSTRAINT `fk_customer_id`
    FOREIGN KEY (`fk_customer_id`)
    REFERENCES `service_management`.`CUSTOMERS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `service_management`.`SERVICES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `service_management`.`SERVICES` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fk_customer_id` INT NOT NULL,
  `fk_device_id` INT NULL,
  `description` TEXT(500) NOT NULL,
  `status` VARCHAR(20) NOT NULL,
  `start_date` DATETIME NULL,
  `end_date` DATETIME NULL,
  `cost` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_customer_id_idx` (`fk_customer_id` ASC) VISIBLE,
  INDEX `fk_device_id_idx` (`fk_device_id` ASC) VISIBLE,
  CONSTRAINT `fk_customer_id`
    FOREIGN KEY (`fk_customer_id`)
    REFERENCES `service_management`.`CUSTOMERS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_device_id`
    FOREIGN KEY (`fk_device_id`)
    REFERENCES `service_management`.`DEVICES` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
